//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekstraklasa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Druzyna
    {
        public Druzyna()
        {
            this.Punkty1 = new HashSet<Punkty>();
            this.Zawodnik = new HashSet<Zawodnik>();
            this.Mecz = new HashSet<Mecz>();
        }
    
        public int Id_D { get; set; }
        public string Trener { get; set; }
        public int Punkty { get; set; }
        public string Nazwa { get; set; }
    
        public virtual ICollection<Punkty> Punkty1 { get; set; }
        public virtual ICollection<Zawodnik> Zawodnik { get; set; }
        public virtual ICollection<Mecz> Mecz { get; set; }
    }
}
