//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekstraklasa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mecz
    {
        public Mecz()
        {
            this.Punkty = new HashSet<Punkty>();
            this.Druzyna = new HashSet<Druzyna>();
        }
    
        public int Id_M { get; set; }
        public byte Odbyty { get; set; }
        public System.DateTime Kiedy { get; set; }
    
        public virtual ICollection<Punkty> Punkty { get; set; }
        public virtual ICollection<Druzyna> Druzyna { get; set; }
    }
}
