//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekstraklasa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EkstraklasaEntities : DbContext
    {
        public EkstraklasaEntities()
            : base("name=EkstraklasaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Druzyna> Druzyna { get; set; }
        public DbSet<Klient> Klient { get; set; }
        public DbSet<Mecz> Mecz { get; set; }
        public DbSet<Punkty> Punkty { get; set; }
        public DbSet<Zawodnik> Zawodnik { get; set; }
    }
}
