//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekstraklasa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Punkty
    {
        public int Id_P { get; set; }
        public int Id_D { get; set; }
        public int Id_M { get; set; }
        public int Punkty1 { get; set; }
    
        public virtual Druzyna Druzyna { get; set; }
        public virtual Mecz Mecz { get; set; }
    }
}
