//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekstraklasa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zawodnik
    {
        public int Id_Z { get; set; }
        public Nullable<int> Id_D { get; set; }
        public int KartkiZolte { get; set; }
        public int KartkiCzerwone { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Pozycja { get; set; }
    
        public virtual Druzyna Druzyna { get; set; }
    }
}
